### ISSUE TITLE
opendmarc-1.3.2: warnings from the clang compiler

### ISSUE THREAD

**Issue by hdatma** [trusteddomainproject/OpenDMARC#41] opened 2019-02-25 17:21 UTC
```
opendmarc: OpenDMARC Filter v1.3.2
	SMFI_VERSION 0x1000001
	libmilter version 1.0.1
	Active code options:
		WITH_SPF
		WITH_SPF2
```

[compiler-stderr.log](https://github.com/trusteddomainproject/OpenDMARC/files/2901659/compiler-stderr.log)

**Comment by martinbogo** [comment] 2020-05-22 14:50
Cannot reproduce using current build.  Closing issue.

**Closed by martinbogo** 2020-05-22 14:50 UTC
